"""Fixed vocab shared by models, schemas and services.

Plain string constants rather than DB-level enums, so the seed data and the
demo reset stay simple to read and edit.
"""

ROLE_EMPLOYEE = "EMPLOYEE"
ROLE_HOD = "HOD"
ROLE_QA = "QA"
ROLE_ADMIN = "ADMIN"
ROLE_IT = "IT"
USER_ROLES = [ROLE_EMPLOYEE, ROLE_HOD, ROLE_QA, ROLE_ADMIN, ROLE_IT]

APPROVER_TYPE_HOD = "HOD"
APPROVER_TYPE_QA = "QA"
APPROVER_TYPES = [APPROVER_TYPE_HOD, APPROVER_TYPE_QA]

STATUS_PENDING_HOD = "PENDING_HOD"
STATUS_PENDING_QA = "PENDING_QA"
STATUS_IT_PENDING = "IT_PENDING"
STATUS_IT_COMPLETED = "IT_COMPLETED"
STATUS_REJECTED = "REJECTED"

REQUEST_STATUSES = [
    STATUS_PENDING_HOD,
    STATUS_PENDING_QA,
    STATUS_IT_PENDING,
    STATUS_IT_COMPLETED,
    STATUS_REJECTED,
]
