"""Fixed vocab shared by models, schemas and services.

Plain string constants rather than DB-level enums, so the seed data and the
demo reset stay simple to read and edit.
"""

ROLE_EMPLOYEE = "EMPLOYEE"
ROLE_HOD = "HOD"
ROLE_QA = "QA"
ROLE_ADMIN = "ADMIN"
ROLE_IT = "IT"
USER_ROLES = [ROLE_EMPLOYEE, ROLE_HOD, ROLE_QA, ROLE_ADMIN, ROLE_IT]

APPROVER_TYPE_HOD = "HOD"
APPROVER_TYPE_QA = "QA"
APPROVER_TYPES = [APPROVER_TYPE_HOD, APPROVER_TYPE_QA]

STATUS_PENDING_HOD = "PENDING_HOD"
STATUS_PENDING_QA = "PENDING_QA"
STATUS_IT_PENDING = "IT_PENDING"
STATUS_PENDING_USER_ACK = "PENDING_USER_ACK"
STATUS_IT_COMPLETED = "IT_COMPLETED"
STATUS_REJECTED = "REJECTED"

REQUEST_STATUSES = [
    STATUS_PENDING_HOD,
    STATUS_PENDING_QA,
    STATUS_IT_PENDING,
    STATUS_PENDING_USER_ACK,
    STATUS_IT_COMPLETED,
    STATUS_REJECTED,
]

# Generalized UAM workflow vocabulary from the UAM Workflow document.
UAM_ROLES = [
    "INITIATOR",
    "REVIEWER",
    "DEPARTMENT_APPROVER",
    "QA_APPROVER",
    "IT_EXECUTOR",
    "INVENTORY_MANAGER",
    "INVENTORY_REQUESTOR",
]
UAM_TEMPLATES = ["MANUFACTURING", "QC", "ERP"]
UAM_ASSET_TYPES = ["EQUIPMENT", "SOFTWARE"]
UAM_ACTIONS = ["CREATE", "MODIFY", "DEACTIVATE", "ACTIVATE", "UNLOCK", "CHANGE_PASSWORD"]
UAM_STATUS_DRAFT = "DRAFT"
UAM_STATUS_PENDING_REVIEW = "PENDING_REVIEW"
UAM_STATUS_PENDING_DEPARTMENT = "PENDING_DEPARTMENT_APPROVAL"
UAM_STATUS_PENDING_QA = "PENDING_QA_APPROVAL"
UAM_STATUS_PENDING_EXECUTION = "PENDING_EXECUTION"
UAM_STATUS_PENDING_ACK = "PENDING_INITIATOR_ACK"
UAM_STATUS_CORRECTION = "CORRECTION_REQUIRED"
UAM_STATUS_SUSPENDED = "SUSPENDED"
UAM_STATUS_CANCELLED = "CANCELLED"
UAM_STATUS_COMPLETED = "COMPLETED"
UAM_STATUS_REJECTED = "REJECTED"
UAM_REQUEST_STATUSES = [
    UAM_STATUS_DRAFT, UAM_STATUS_PENDING_REVIEW, UAM_STATUS_PENDING_DEPARTMENT,
    UAM_STATUS_PENDING_QA, UAM_STATUS_PENDING_EXECUTION, UAM_STATUS_PENDING_ACK,
    UAM_STATUS_CORRECTION, UAM_STATUS_SUSPENDED, UAM_STATUS_CANCELLED,
    UAM_STATUS_COMPLETED, UAM_STATUS_REJECTED,
]
