import { FormEvent, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";
import { useAuth } from "../context/AuthContext";
import { Button } from "../components/ui/Button";
import { Card, CardBody, CardHeader, CardTitle } from "../components/ui/Card";
import { Field, FieldLabel, Input, Textarea } from "../components/ui/Input";
import { useToast } from "../components/ui/Toast";

export function CreateUAMRequestPage() {
  const { currentUser } = useAuth(); const navigate = useNavigate(); const { showToast } = useToast();
  const [template, setTemplate] = useState("MANUFACTURING"); const [assetType, setAssetType] = useState("EQUIPMENT"); const [assetCode, setAssetCode] = useState(""); const [role, setRole] = useState(""); const [action, setAction] = useState("CREATE"); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (template === "MANUFACTURING") setAssetType("EQUIPMENT"); else setAssetType("SOFTWARE"); }, [template]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!currentUser) return; setBusy(true); try { const req = await api.createUAMRequest({ template, asset_type: assetType, asset_code: assetCode, requested_role: role, action, reason, plant: currentUser.plant, qa_approver_id: template === "MANUFACTURING" ? "QA001" : undefined, reviewer_id: "HOD001", it_executor_id: "IT001", form_data: { template } }); showToast(`${req.request_code} submitted for review.`); navigate(`/uam/requests/${req.request_code}`); } catch (err) { showToast(err instanceof Error ? err.message : "Request failed", "error"); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-3xl space-y-6"><div><h1 className="text-xl font-bold text-slate-900">Create UAM request</h1><p className="text-sm text-slate-500">Select a template and action; fields are routed through the configured approval path.</p></div><Card><CardHeader><CardTitle>Request details</CardTitle></CardHeader><CardBody><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel>Template</FieldLabel><select className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={template} onChange={e => setTemplate(e.target.value)}><option value="MANUFACTURING">Manufacturing</option><option value="QC">QC</option><option value="ERP">ERP</option></select></Field><Field><FieldLabel>Asset type</FieldLabel><select className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={assetType} onChange={e => setAssetType(e.target.value)} disabled={template === "MANUFACTURING"}><option value="EQUIPMENT">Equipment</option><option value="SOFTWARE">Software</option></select></Field><Field><FieldLabel>Equipment/software code</FieldLabel><Input required value={assetCode} onChange={e => setAssetCode(e.target.value)} placeholder="EQ-001 or SW-001" /></Field><Field><FieldLabel>Requested role</FieldLabel><Input required value={role} onChange={e => setRole(e.target.value)} placeholder="Analyst / Viewer" /></Field><Field><FieldLabel>Action</FieldLabel><select className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={action} onChange={e => setAction(e.target.value)}>{["CREATE", "MODIFY", "DEACTIVATE", "ACTIVATE", "UNLOCK", "CHANGE_PASSWORD"].map(v => <option key={v}>{v}</option>)}</select></Field></div><Field><FieldLabel>Reason / remarks</FieldLabel><Textarea required rows={5} value={reason} onChange={e => setReason(e.target.value)} placeholder="Describe the business need and requested change..." /></Field><div className="flex justify-end"><Button type="submit" disabled={busy}>{busy ? "Submitting..." : "Submit request"}</Button></div></form></CardBody></Card></div>;
}
