import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { api } from "../lib/api";
import type { UAMRequest } from "../types";
import { Card, CardBody, CardHeader, CardTitle } from "../components/ui/Card";
import { StatusBadge } from "../components/StatusBadge";
import { Button } from "../components/ui/Button";
import { Input, Textarea, Field, FieldLabel } from "../components/ui/Input";
import { useToast } from "../components/ui/Toast";

export function UAMRequestDetailPage() {
  const { code } = useParams<{ code: string }>(); const { showToast } = useToast(); const [request, setRequest] = useState<UAMRequest | null>(null); const [comment, setComment] = useState(""); const [userId, setUserId] = useState(""); const [password, setPassword] = useState(""); const load = () => { if (code) api.getUAMRequest(code).then(setRequest).catch(e => showToast(e.message, "error")); }; useEffect(load, [code]);
  if (!request) return <p className="text-sm text-slate-500">Loading request...</p>;
  const action = async (fn: () => Promise<UAMRequest>, message: string) => { try { await fn(); showToast(message); setComment(""); load(); } catch (e) { showToast(e instanceof Error ? e.message : "Action failed", "error"); } };
  return <div className="mx-auto max-w-4xl space-y-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">UAM request</p><h1 className="text-xl font-bold text-slate-900">{request.request_code}</h1></div><StatusBadge status={request.status} /></div><Card><CardHeader><CardTitle>Request summary</CardTitle></CardHeader><CardBody><div className="grid gap-4 sm:grid-cols-2"><Info label="Initiator" value={`${request.employee_name} (${request.employee_id})`} /><Info label="Plant" value={request.plant} /><Info label="Asset" value={`${request.asset_code} · ${request.asset_type}`} /><Info label="Template / action" value={`${request.template} · ${request.action}`} /><Info label="Requested role" value={request.requested_role} /><Info label="Created" value={new Date(request.created_at).toLocaleString()} /></div><div className="mt-4"><p className="text-xs font-medium text-slate-500">Reason</p><p className="text-sm text-slate-800">{request.reason}</p></div></CardBody></Card>{request.rejection_reason && <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">{request.rejection_reason}</div>}<Card><CardHeader><CardTitle>Workflow action</CardTitle></CardHeader><CardBody className="space-y-4"><Field><FieldLabel>Comment</FieldLabel><Textarea rows={3} value={comment} onChange={e => setComment(e.target.value)} placeholder="Add a review note or correction reason..." /></Field>{request.status === "PENDING_EXECUTION" || request.status === "SUSPENDED" ? <div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel>User ID</FieldLabel><Input value={userId} onChange={e => setUserId(e.target.value)} /></Field><Field><FieldLabel>Temporary password</FieldLabel><Input type="password" value={password} onChange={e => setPassword(e.target.value)} /></Field></div> : null}<div className="flex flex-wrap justify-end gap-2">{["PENDING_REVIEW", "PENDING_DEPARTMENT_APPROVAL", "PENDING_QA_APPROVAL"].includes(request.status) && <><Button variant="secondary" onClick={() => action(() => api.requestUAMCorrection(request.request_code, comment), "Correction requested.")}>Correction required</Button><Button variant="danger" onClick={() => action(() => api.rejectUAMRequest(request.request_code, comment), "Request rejected.")}>Reject</Button><Button onClick={() => action(() => api.approveUAMRequest(request.request_code, comment), "Request approved.")}>Approve</Button></>}{["PENDING_EXECUTION", "SUSPENDED"].includes(request.status) && <Button onClick={() => action(() => api.executeUAMRequest(request.request_code, userId, password, comment), "Execution recorded.")}>Complete execution</Button>}{request.status === "PENDING_INITIATOR_ACK" && <Button onClick={() => action(() => api.acknowledgeUAMRequest(request.request_code, comment), "Request acknowledged and closed.")}>Acknowledge & close</Button>}</div></CardBody></Card></div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-medium text-slate-500">{label}</p><p className="text-sm font-semibold text-slate-800">{value}</p></div>; }
