"""Initial migration

Revision ID: c275a51c5fc1
Revises: 
Create Date: 2026-09-18 22:11:31.550623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c275a51c5fc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('employee_name', sa.String(length=120), nullable=False),
    sa.Column('employee_email', sa.String(length=160), nullable=False),
    sa.Column('employee_department', sa.String(length=80), nullable=False),
    sa.Column('equipment_code', sa.String(length=20), nullable=False),
    sa.Column('equipment_name', sa.String(length=160), nullable=False),
    sa.Column('requested_role', sa.String(length=60), nullable=False),
    sa.Column('hod_id', sa.String(length=20), nullable=False),
    sa.Column('hod_name', sa.String(length=120), nullable=False),
    sa.Column('hod_email', sa.String(length=160), nullable=False),
    sa.Column('qa_id', sa.String(length=20), nullable=False),
    sa.Column('qa_name', sa.String(length=120), nullable=False),
    sa.Column('qa_email', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_stage', sa.String(length=10), nullable=True),
    sa.Column('user_login_id', sa.String(length=100), nullable=True),
    sa.Column('temporary_password', sa.String(length=255), nullable=True),
    sa.Column('it_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('user_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_request_code'), 'access_requests', ['request_code'], unique=True)
    op.create_table('approvers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approver_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvers_approver_code'), 'approvers', ['approver_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=20), nullable=True),
    sa.Column('user_employee_id', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_request_code'), 'audit_logs', ['request_code'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('plant', sa.String(length=20), nullable=False),
    sa.Column('allowed_roles', sa.Text(), nullable=False),
    sa.Column('validation_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_code'), 'equipment', ['equipment_code'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=False),
    sa.Column('recipient_email', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_request_code'), 'notifications', ['request_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('plant', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('action_pin', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notifications_request_code'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_equipment_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_audit_logs_request_code'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approvers_approver_code'), table_name='approvers')
    op.drop_table('approvers')
    op.drop_index(op.f('ix_access_requests_request_code'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
